name: Build project
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
  workflow_dispatch:
jobs:
   build:
    name: Build for WebGL
    runs-on: ubuntu-latest
    steps:
    
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          lfs: true
          
      - uses: actions/cache@v2
        with:
          path: Library
          key: Library-WebGL
          restore-keys: Library-
          
      - uses: game-ci/unity-builder@v2
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
        with:
          targetPlatform: WebGL
          
      - uses: actions/upload-artifact@v2
        with:
          name: Build-WebGL
          path: build/WebGL
          
      - name: Commit files
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
          USER_EMAIL: ${{ secrets.EMAIL }}
          USER_NAME: ${{ secrets.USER_NAME }}
          DESTINATION_REPOSITORY_USERNAME: ${{ secrets.USER_NAME }}
          DESTINATION_REPOSITORY_NAME: EpicSpaceFix
          DESTINATION_BRANCH: main
          OUTPUT_BRANCH: main
          DESTINATION_FOLDER: ./
          SOURCE_FILE: build/WebGL/WebGL/.
        run: |
          CLONE_DIR=$(mktemp -d)
          
          echo "Cloning destination git repository"
          git config --global user.email "$USER_EMAIL"
          git config --global user.name "$USER_NAME"
          git clone --single-branch --branch $DESTINATION_BRANCH "https://$USER_NAME:$API_TOKEN_GITHUB@github.com/$DESTINATION_REPOSITORY_USERNAME/$DESTINATION_REPOSITORY_NAME.git" "$CLONE_DIR"
          echo "Copying contents to git repo"
          mkdir -p $CLONE_DIR/$DESTINATION_FOLDER
          cp -R "$SOURCE_FILE" "$CLONE_DIR/$DESTINATION_FOLDER"
          cd "$CLONE_DIR"
          
          echo "Adding git commit"
          git add .
          if git status | grep -q "Changes to be committed"
          then
            git commit --message "Update from https://github.com/${GITHUB_REPOSITORY}/commit/${GITHUB_SHA}"
            echo "Pushing git commit"
            git push -u origin HEAD:$OUTPUT_BRANCH
          else
            echo "No changes detected"
          fi